### ISSUE TITLE
Typos in install guide

### ISSUE THREAD

**Issue by srpwnd** [PedramNavid/dbtpal#14]
There are two typos in your installation guide:

1. It seems like you recently renamed your GitHub account so

```lua
use {'pdrmnvd/dbtpal',
...
```
should be
```lua
use {'PedramNavid/dbtpal',
...
```

2. Small typo in Telescope extension:

```lua
require'telescope'.load_extension('dbt_pal')
```
should be
```lua
require'telescope'.load_extension('dbtpal')
```

This is not very big issue, just wanted to let you know about these so other users can copy-paste the config without issues :) I myself am not very efficient with neovim and it took me some time to debug this.

**Comment by PedramNavid** [comment]
Hey @srpwnd thanks so much for finding these! I can fix them, or if you'd like to be the first contributor, I can walk you through submitting a PR to get these fixed. If that's something you're up for, let me know and we can find a way to do that together.

**Comment by srpwnd** [comment]
@PedramNavid, I would love to contribute! Just didn't feel like fixing a typo in readme was worth opening a PR.

But if thats something you'd like I could get to it in the morning.

**Comment by PedramNavid** [comment]
Definitely worth a PR!
