### ISSUE TITLE
Syntax highlighting incorrectly formatting as a string

### ISSUE THREAD

**Issue by deanmorin** [PedramNavid/dbtpal#24]
A single apostrophes in a comment will make all of the subsequent sql be highlighted as a string:

```sql
select
  1,
  -- apostrophe in comment '
  2
```
![image](https://github.com/PedramNavid/dbtpal/assets/416052/5c2cc728-9abb-4fb1-a2e9-d319d99524af)

```sql
select
  1,
  /* apostrophe in comment ' */
  2
```
![image](https://github.com/PedramNavid/dbtpal/assets/416052/9e09dc9b-3be8-49ab-987b-7db279f4adb2)

Quoted macro calls will do the same thing:

```sql
{{
  config(
    post_hook = "{{ my_post_hook() }}",
  )
}}

select 1
```
![image](https://github.com/PedramNavid/dbtpal/assets/416052/d39234bc-18d8-4663-bf36-16956fb2c306)

It still happens with just `"{{ }}"`, it seems to be the double braces. If you remove one of the pairs it stops happening. It also stops happening if you remove the surrounding quotes.

**Comment by cmpadden** [comment]
There is a treesitter syntax from dbt-labs, however, they currently state that it is incomplete. We may want to keep our eyes on it for updates.

https://github.com/dbt-labs/tree-sitter-jinja2

> This Jinja2 grammar for tree-sitter is currently incomplete.

**Comment by PedramNavid** [comment]
Oddly, I don't get this behavior with the first two examples:
<img width="322" alt="image" src="https://github.com/PedramNavid/dbtpal/assets/1045990/8c9cc076-7ae1-4dbb-95df-b9d7df372946">
<img width="313" alt="image" src="https://github.com/PedramNavid/dbtpal/assets/1045990/ee024415-e6aa-455e-b911-5ee4e2da80dc">

However, #0950ceb88ae898a23f78a4d12fbeeee4cb5dad5e fixes the issue with nested jinja templates:

<img width="388" alt="image" src="https://github.com/PedramNavid/dbtpal/assets/1045990/9421a140-8e23-4418-802e-05c887817b2b">

Let me know if you still have issues with the first two.
