### ISSUE TITLE
dbt.vim overrides default sql.vim syntax highlighting

### ISSUE THREAD

**Issue by Xemptuous** [PedramNavid/dbtpal#28]
the file `dbt.vim` breaks syntax highlighting (atleast on my setup) unless I comment out either of these two lines:
```vim
syn match   dbtJinjaOperator    "{{\|}}\|{%\|%}"
syn cluster dbtJinja           contains=dbtJinjaOperator,dbtJinjaFunction,dbtJinjaString
```
It looks like 0950ceb caused this issue, because when I revert the `syn region dbtJinjaTemplate` line to the previous version, it works.

**Comment by PedramNavid** [comment]
Oof. Syntax is really hard.  You can also try setting     custom_dbt_syntax_enabled = false

**Comment by Xemptuous** [comment]
That seems to have helped to an extent (better than before, and having to modify the source file), but I still have most sql keywords not being highlighted anytime there is jinja syntax before them in the file. It's as though it hijacks it and doesn't go back to using the default SQL syntax between jinja blocks.

**Comment by PedramNavid** [comment]
ah very odd @Xemptuous, I think I know the issue. Will try and get a fix up. Thanks for reporting this!

**Comment by PedramNavid** [comment]
> That seems to have helped to an extent (better than before, and having to modify the source file), but I still have most sql keywords not being highlighted anytime there is jinja syntax before them in the file. It's as though it hijacks it and doesn't go back to using the default SQL syntax between jinja blocks.

Can you try opening up a SQL file with jinja please and let me know the output of this:

```
:set ft?
```

**Comment by Xemptuous** [comment]
> 
> Can you try opening up a SQL file with jinja please and let me know the output of this:
> 
> ```
> :set ft?
> ```
it's set to dbt.

Still have this issue, to where using `ft=sql` makes things much more readable, but then no jinja gets highlighted. 

Looks like all dbt stuff is highlighted properly, but as soon as a jinja block happens, almost none of the sql stuff afterwards is highlighted.

![image](https://github.com/PedramNavid/dbtpal/assets/99044751/0f73dd8f-e66d-40cb-835e-90a75329ba35)

**Comment by MinhTriet-TO** [comment]
Hello @PedramNavid, i have the same problem here. I use `nvim-treesitter` for syntax highlighting and when i install `dbtpal`, it just messed up the syntax highlighting. Everything worked well until your latest commit https://github.com/PedramNavid/dbtpal/commit/0950ceb88ae898a23f78a4d12fbeeee4cb5dad5e
Do you intend to follow this issue and fix it ? Thanks in advance :smile:

**Comment by PedramNavid** [comment]
Hi @MinhTriet-TO  and @Xemptuous. I finally had some time to look at this and I believe I fixed it in [this commit](https://github.com/PedramNavid/dbtpal/commit/e9136487194a17e9a5f40644a65b2d5f0e899446)
I had an empty setup call that would reset your preferences. Hope this helps, sorry for the delay, my notifications are a bit of a mess.
