### ISSUE TITLE
Go to file (gf) doesnt work in version v0.0.6

### ISSUE THREAD

**Issue by vanducng** [PedramNavid/dbtpal#33]
hi @PedramNavid , thank you for a great plugin. Im using a lot the jump to file feature. However, I noted that it doesnt work anymore in new version 0.0.6. Im using MacOS.

Hope that you can give it a fix or advice to update the config to make it work. I can help to test it out.

**Comment by PedramNavid** [comment]
@vanducng thanks for reporting this! I just pushed a commit that should fix this, could you double check?

**Comment by vanducng** [comment]
> @vanducng thanks for reporting this! I just pushed a commit that should fix this, could you double check?

You are super. It is working again. Thank you.
